name: Windows Build (Push)

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Cache NW.js
        uses: actions/cache@v4
        with:
          path: cache/
          key: nwjs-release-${{ runner.os }}-${{ hashFiles('gulpfile.js') }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: node_modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn gulp release --win64

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Betaflight-Configurator-Windows
          path: release/
          retention-days: 90
